//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bds.Areas.Cpanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BDS_LOAIBDS
    {
        public int IDBDS { get; set; }
        public Nullable<int> THUTU { get; set; }
        public string TENBDS { get; set; }
        public Nullable<int> HIENTHI { get; set; }
        public Nullable<int> HIEULUC { get; set; }
    }
}
