//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bds.Areas.Cpanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIET_TT
    {
        public int ChiTietTTID { get; set; }
        public Nullable<int> IDMuaBan { get; set; }
        public Nullable<int> IDThuocTinh { get; set; }
    
        public virtual BDS_MUABAN BDS_MUABAN { get; set; }
        public virtual THUOCTINH THUOCTINH { get; set; }
    }
}
