//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bds.Areas.Cpanel.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_BDSAdminEntities : DbContext
    {
        public DB_BDSAdminEntities()
            : base("name=DB_BDSAdminEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BDS_DIENTICH> BDS_DIENTICH { get; set; }
        public virtual DbSet<BDS_DM_GIAODICH> BDS_DM_GIAODICH { get; set; }
        public virtual DbSet<BDS_GIA> BDS_GIA { get; set; }
        public virtual DbSet<BDS_HUONGNHA> BDS_HUONGNHA { get; set; }
        public virtual DbSet<BDS_LOAIBDS> BDS_LOAIBDS { get; set; }
        public virtual DbSet<BDS_MUABAN> BDS_MUABAN { get; set; }
        public virtual DbSet<BDS_TINTUC> BDS_TINTUC { get; set; }
        public virtual DbSet<CHITIET_TT> CHITIET_TT { get; set; }
        public virtual DbSet<DUAN> DUANs { get; set; }
        public virtual DbSet<DUAN_HINH> DUAN_HINH { get; set; }
        public virtual DbSet<DUAN_LOAI> DUAN_LOAI { get; set; }
        public virtual DbSet<DUONGPHO> DUONGPHOes { get; set; }
        public virtual DbSet<GIOITHIEU> GIOITHIEUx { get; set; }
        public virtual DbSet<INFORMATION> INFORMATION { get; set; }
        public virtual DbSet<MENU> MENUs { get; set; }
        public virtual DbSet<THANHVIEN> THANHVIENs { get; set; }
        public virtual DbSet<THUOCTINH> THUOCTINHs { get; set; }
        public virtual DbSet<TINHTHANH> TINHTHANHs { get; set; }
    }
}
