//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bds.Areas.Cpanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUAN_HINH
    {
        public decimal IDTT { get; set; }
        public Nullable<int> THUTU { get; set; }
        public int IDH { get; set; }
        public string TENHINH { get; set; }
        public string HINHNHO { get; set; }
        public string HINHLON { get; set; }
        public string MOTA { get; set; }
        public Nullable<int> HIEULUC { get; set; }
        public Nullable<int> HIENTHI { get; set; }
    }
}
