//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bds.Areas.Cpanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUAN
    {
        public Nullable<int> IDLOAI { get; set; }
        public Nullable<int> THUTU { get; set; }
        public decimal IDTT { get; set; }
        public string TIEUDE { get; set; }
        public string TOMTAT { get; set; }
        public string NOIDUNG { get; set; }
        public string HINHNHO { get; set; }
        public string HINHLON { get; set; }
        public Nullable<System.DateTime> NGAY { get; set; }
        public Nullable<int> TINNOIBAT { get; set; }
        public Nullable<int> HIENTHI { get; set; }
        public Nullable<int> HIEULUC { get; set; }
        public Nullable<int> SOLANXEM { get; set; }
    }
}
