//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bds.Areas.Cpanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUAN_LOAI
    {
        public int IDLOAI { get; set; }
        public Nullable<int> THUTU { get; set; }
        public string TENLOAI { get; set; }
        public Nullable<int> HIENTHI { get; set; }
        public Nullable<int> HIEULUC { get; set; }
        public Nullable<int> IDCHA { get; set; }
        public string URL { get; set; }
        public Nullable<System.DateTime> NGAY { get; set; }
        public Nullable<int> CAP { get; set; }
        public string HINHANH { get; set; }
        public string NOIDUNG { get; set; }
        public Nullable<int> TINNOIBAT { get; set; }
    }
}
