//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bds.Areas.Cpanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUONGPHO
    {
        public int IDDP { get; set; }
        public string TenTT { get; set; }
        public Nullable<int> IDTT { get; set; }
        public Nullable<int> Cap { get; set; }
        public Nullable<int> DemChoThue { get; set; }
        public Nullable<int> DemMuaban { get; set; }
        public Nullable<int> ThuTu { get; set; }
        public string url { get; set; }
    
        public virtual TINHTHANH TINHTHANH { get; set; }
    }
}
