//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bds.Areas.Cpanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MENU()
        {
            this.BDS_MuaBan = new HashSet<BDS_MuaBan>();
            this.BDS_TinTuc = new HashSet<BDS_TinTuc>();
        }
    
        public int IdMenu { get; set; }
        public string TenMenu { get; set; }
        public Nullable<int> IdCha { get; set; }
        public Nullable<int> ThuTu { get; set; }
        public Nullable<int> HienThi { get; set; }
        public Nullable<bool> IsMenu { get; set; }
        public string url { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BDS_MuaBan> BDS_MuaBan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BDS_TinTuc> BDS_TinTuc { get; set; }
    }
}
