//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bds.Areas.Cpanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU
    {
        public int IdMenu { get; set; }
        public string TenMenu { get; set; }
        public Nullable<int> IdCha { get; set; }
        public Nullable<int> ThuTu { get; set; }
        public Nullable<int> HienThi { get; set; }
        public Nullable<bool> IsMenu { get; set; }
        public string url { get; set; }
    }
}
