//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bds.Areas.Cpanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyMuaBan
    {
        public int ProMuaID { get; set; }
        public Nullable<int> PropertyID { get; set; }
        public Nullable<int> MuaBanID { get; set; }
    
        public virtual BDS_MuaBan BDS_MuaBan { get; set; }
        public virtual Property Property { get; set; }
    }
}
