//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bds.Areas.Cpanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANHVIEN
    {
        public int idTV { get; set; }
        public string TenTruyCap { get; set; }
        public string MatKhau { get; set; }
        public string HoTen { get; set; }
        public string DiaChi { get; set; }
        public string SoDiDong { get; set; }
        public string EmailLH { get; set; }
        public Nullable<int> TinhTrang { get; set; }
        public Nullable<int> VIP { get; set; }
        public Nullable<System.DateTime> LanDangNhapCuoi { get; set; }
    }
}
